[package]
edition = "2021"
name = "myip"
version = "0.1.0"

[dependencies]
anyhow = "1.0.75"
futures = "0.3.28"
reqwest = "0.11.20"
tokio = {version = "1.32.0", features = ["macros", "rt-multi-thread"]}
